# 1984 orwellian theme by Bertie Blackman, https://github.com/covertbert/iterm2-1984/

foreground #f1f1f1
# background #2e2923
background #000000
selection_foreground #000000
selection_background #3fc4ce
color0 #000000
color1 #a27460
color2 #c17759
color3 #e68b54
color4 #5c7796
color5 #8f667c
color6 #6183a0
color7 #9bbede
color8 #000000
color9 #92766a
color10 #b37a67
color11 #d48c60
color12 #68748a
color13 #807279
color14 #6b7f90
color15 #abbac8

# URL styles
url_color #e74946
url_style single

# Cursor styles
cursor #cf6a4b
